### ISSUE TITLE
Ffmpeg encoding configuration structure needs work

### ISSUE THREAD

**Issue by in03** [in03/proxima#216]
Before we introduce multiple presets, we really need to figure out how best to structure ffmpeg settings in YAML (or eventually TOML):

```yaml
proxy:
  ffmpeg_loglevel: error # "quiet", "panic", "fatal", "error", "warning", "info", "verbose", "debug"
  codec: prores
  vertical_res: "720"
  profile: "0" #422 proxy
  pix_fmt: yuv422p
  audio_codec: pcm_s16le
  audio_samplerate: "48000"
  misc_args: [-hide_banner, -stats]
  ext: .mov
```

This works for our DNxHD preset, but it's completely restrictive. `misc_args` for example gives no clue as to where in the command structure the args are inserted? At the end? Beginning? Before or after `-i` or `-o`? That all plays a huge part in how the command is intepreted.

We do want to keep the syntax simple, but we can't really simplify or abstract ffmpeg commands without losing flexibility.
Let's look into how others are doing this for inspiration.
